version = 3.11.5
style = defaultWithAlign
runner.dialect = scala213
maxColumn = 120
rewrite.rules = [RedundantBraces,RedundantParens,PreferCurlyFors]
danglingParentheses.preset = true
lineEndings=preserve