addSbtPlugin("com.geirsson"              % "sbt-ci-release"    % "1.5.7")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"        % "5.6.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.1.20")
addSbtPlugin("com.eed3si9n"              % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("com.indoorvivants"         % "sbt-commandmatrix" % "0.0.3")
