addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("de.heikoseeberger"                 % "sbt-header"        % "5.6.0")
addSbtPlugin("org.jetbrains.scala"               % "sbt-ide-settings"  % "1.1.1")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"      % "2.4.3")
addSbtPlugin("io.github.davidgregory084"         % "sbt-tpolecat"      % "0.1.20")
addSbtPlugin("com.eed3si9n"                      % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("com.indoorvivants"                 % "sbt-commandmatrix" % "0.0.4")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"  % "3.0.0")
