addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"   % "1.5.10")
addSbtPlugin("de.heikoseeberger"                 % "sbt-header"       % "5.6.5")
addSbtPlugin("org.jetbrains.scala"               % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("io.github.davidgregory084"         % "sbt-tpolecat"     % "0.2.2")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.2")
