name: PR Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command: [ testCore, testScalaTest, testZioTest, testMunit, testWeaver, testExamples ]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1 #https://eed3si9n.com/setup-sbt/
      - run: sbt ${{ matrix.command }}
